### ISSUE TITLE
Login fxml view

### ISSUE THREAD

**Issue by Bokaiii** [creditoro/desktop-client#22]

**Comment by nymann** [comment]
This is a good enough state for now in my opinion @Bokaiii .

In the future we could add the following:
- notification popup for login responses instead of the basic text there is now.
- email input validation via binding (so that we display a red cross or something when the email field is not filled with a valid email).

**Comment by nymann** [comment]
Feel free to move it to Closed if you agree, and open new issues for my suggestions.
